CREATE TABLE `audio_verifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`fileName` varchar(512) NOT NULL,
	`fileSize` bigint NOT NULL,
	`fileUrl` text NOT NULL,
	`fileKey` varchar(512) NOT NULL,
	`duration` int,
	`sampleRate` int,
	`bitDepth` int,
	`channels` int,
	`codec` varchar(64),
	`fileHash` varchar(128),
	`verdict` enum('observed','not_observed'),
	`crgStatus` varchar(64),
	`primaryExceededAxis` varchar(64),
	`timelineMarkers` json,
	`analysisData` json,
	`status` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `audio_verifications_id` PRIMARY KEY(`id`)
);
