import { Button } from "@/components/ui/button";
import { FileJson, FileSpreadsheet, FileText, FileType } from "lucide-react";

interface ExportData {
  fileName: string;
  fileSize: number;
  duration: number | null;
  sampleRate: number | null;
  bitDepth: number | null;
  channels: number | null;
  codec: string | null;
  fileHash: string | null;
  verdict: "observed" | "not_observed" | null;
  crgStatus: string | null;
  primaryExceededAxis: string | null;
  timelineMarkers: { timestamp: number; type: string }[];
  analysisTimestamp: string;
}

interface ExportPanelProps {
  data: ExportData | null;
  disabled?: boolean;
}

// ONLY allowed verdict texts
const VERDICT_TEXTS = {
  observed: "AI signal evidence was observed.",
  not_observed: "AI signal evidence was not observed.",
} as const;

function formatDuration(ms: number): string {
  const totalSeconds = Math.floor(ms / 1000);
  const mins = Math.floor(totalSeconds / 60);
  const secs = totalSeconds % 60;
  return `${mins}:${secs.toString().padStart(2, "0")}`;
}

function generatePDFContent(data: ExportData): string {
  // Generate HTML content for PDF
  const verdictText = data.verdict ? VERDICT_TEXTS[data.verdict] : "Pending";

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>DetectX Audio Verification Report</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
    h1 { color: #0d9488; border-bottom: 2px solid #0d9488; padding-bottom: 10px; }
    h2 { color: #555; margin-top: 30px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }
    th { background: #f5f5f5; }
    .verdict { font-size: 18px; padding: 20px; background: #f0fdf4; border-left: 4px solid #22c55e; margin: 20px 0; }
    .verdict.observed { background: #fffbeb; border-left-color: #f59e0b; }
    .footer { margin-top: 40px; font-size: 12px; color: #888; }
  </style>
</head>
<body>
  <h1>DetectX Audio Verification Report</h1>
  <p><strong>Generated:</strong> ${data.analysisTimestamp}</p>
  
  <h2>File Information</h2>
  <table>
    <tr><th>Filename</th><td>${data.fileName}</td></tr>
    <tr><th>File Size</th><td>${(data.fileSize / 1024 / 1024).toFixed(2)} MB</td></tr>
    <tr><th>Duration</th><td>${data.duration ? formatDuration(data.duration) : "N/A"}</td></tr>
    <tr><th>Sample Rate</th><td>${data.sampleRate ? `${data.sampleRate} Hz` : "N/A"}</td></tr>
    <tr><th>Bit Depth</th><td>${data.bitDepth ? `${data.bitDepth}-bit` : "N/A"}</td></tr>
    <tr><th>Channels</th><td>${data.channels || "N/A"}</td></tr>
    <tr><th>Codec</th><td>${data.codec || "N/A"}</td></tr>
    <tr><th>SHA-256</th><td style="font-family: monospace; font-size: 12px;">${data.fileHash || "N/A"}</td></tr>
  </table>
  
  <h2>Verification Result</h2>
  <div class="verdict ${data.verdict === "observed" ? "observed" : ""}">
    ${verdictText}
  </div>
  
  <table>
    <tr><th>CR-G Status</th><td>${data.crgStatus || "N/A"}</td></tr>
    ${data.primaryExceededAxis ? `<tr><th>Primary Exceeded Axis</th><td>${data.primaryExceededAxis}</td></tr>` : ""}
  </table>
  
  ${data.timelineMarkers.length > 0 ? `
  <h2>Timeline Events</h2>
  <table>
    <tr><th>#</th><th>Type</th><th>Timestamp</th></tr>
    ${data.timelineMarkers.map((m, i) => `
      <tr>
        <td>${i + 1}</td>
        <td>${m.type}</td>
        <td>${formatDuration(m.timestamp)}</td>
      </tr>
    `).join("")}
  </table>
  ` : ""}
  
  <div class="footer">
    <p>This report contains structural signal evidence only. The system does not estimate probability, attribute authorship, or reference any specific AI model names.</p>
    <p>Generated by DetectX Audio — Audio AI Signal Verification</p>
  </div>
</body>
</html>
  `;
}

function generateJSON(data: ExportData): string {
  const report = {
    reportVersion: "1.0.0",
    generatedAt: data.analysisTimestamp,
    file: {
      name: data.fileName,
      size: data.fileSize,
      duration: data.duration,
      sampleRate: data.sampleRate,
      bitDepth: data.bitDepth,
      channels: data.channels,
      codec: data.codec,
      hash: data.fileHash,
    },
    verification: {
      verdict: data.verdict ? VERDICT_TEXTS[data.verdict] : null,
      verdictCode: data.verdict,
      crgStatus: data.crgStatus,
      primaryExceededAxis: data.primaryExceededAxis,
    },
    timelineEvents: data.timelineMarkers,
  };
  return JSON.stringify(report, null, 2);
}

function generateCSV(data: ExportData): string {
  const lines = [
    "Field,Value",
    `Filename,"${data.fileName}"`,
    `File Size,${data.fileSize}`,
    `Duration,${data.duration || ""}`,
    `Sample Rate,${data.sampleRate || ""}`,
    `Bit Depth,${data.bitDepth || ""}`,
    `Channels,${data.channels || ""}`,
    `Codec,"${data.codec || ""}"`,
    `Hash,"${data.fileHash || ""}"`,
    `Verdict,"${data.verdict ? VERDICT_TEXTS[data.verdict] : ""}"`,
    `CR-G Status,"${data.crgStatus || ""}"`,
    `Primary Exceeded Axis,"${data.primaryExceededAxis || ""}"`,
    `Analysis Timestamp,"${data.analysisTimestamp}"`,
    "",
    "Timeline Events",
    "Index,Type,Timestamp (ms)",
    ...data.timelineMarkers.map((m, i) => `${i + 1},"${m.type}",${m.timestamp}`),
  ];
  return lines.join("\n");
}

function generateMarkdown(data: ExportData): string {
  const verdictText = data.verdict ? VERDICT_TEXTS[data.verdict] : "Pending";

  let md = `# DetectX Audio Verification Report

**Generated:** ${data.analysisTimestamp}

## File Information

| Field | Value |
|-------|-------|
| Filename | ${data.fileName} |
| File Size | ${(data.fileSize / 1024 / 1024).toFixed(2)} MB |
| Duration | ${data.duration ? formatDuration(data.duration) : "N/A"} |
| Sample Rate | ${data.sampleRate ? `${data.sampleRate} Hz` : "N/A"} |
| Bit Depth | ${data.bitDepth ? `${data.bitDepth}-bit` : "N/A"} |
| Channels | ${data.channels || "N/A"} |
| Codec | ${data.codec || "N/A"} |
| SHA-256 | \`${data.fileHash || "N/A"}\` |

## Verification Result

> **${verdictText}**

| Metric | Value |
|--------|-------|
| CR-G Status | ${data.crgStatus || "N/A"} |
${data.primaryExceededAxis ? `| Primary Exceeded Axis | ${data.primaryExceededAxis} |` : ""}

`;

  if (data.timelineMarkers.length > 0) {
    md += `## Timeline Events

| # | Type | Timestamp |
|---|------|-----------|
${data.timelineMarkers.map((m, i) => `| ${i + 1} | ${m.type} | ${formatDuration(m.timestamp)} |`).join("\n")}

`;
  }

  md += `---

*This report contains structural signal evidence only. The system does not estimate probability, attribute authorship, or reference any specific AI model names.*

*Generated by DetectX Audio — Audio AI Signal Verification*
`;

  return md;
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function ExportPanel({ data, disabled = false }: ExportPanelProps) {
  const handleExportPDF = () => {
    if (!data) return;
    const content = generatePDFContent(data);
    // Open in new window for printing
    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(content);
      printWindow.document.close();
      printWindow.print();
    }
  };

  const handleExportJSON = () => {
    if (!data) return;
    const content = generateJSON(data);
    const baseName = data.fileName.replace(/\.[^/.]+$/, "");
    downloadFile(content, `${baseName}_report.json`, "application/json");
  };

  const handleExportCSV = () => {
    if (!data) return;
    const content = generateCSV(data);
    const baseName = data.fileName.replace(/\.[^/.]+$/, "");
    downloadFile(content, `${baseName}_report.csv`, "text/csv");
  };

  const handleExportMarkdown = () => {
    if (!data) return;
    const content = generateMarkdown(data);
    const baseName = data.fileName.replace(/\.[^/.]+$/, "");
    downloadFile(content, `${baseName}_report.md`, "text/markdown");
  };

  const isDisabled = disabled || !data || !data.verdict;

  return (
    <div className="forensic-panel">
      <div className="forensic-panel-header">Export Report</div>
      <div className="forensic-panel-content">
        <div className="grid grid-cols-2 gap-3">
          <Button
            variant="outline"
            className="h-auto py-3 flex flex-col items-center gap-2"
            onClick={handleExportPDF}
            disabled={isDisabled}
          >
            <FileType className="w-5 h-5" />
            <span className="text-xs">PDF</span>
          </Button>

          <Button
            variant="outline"
            className="h-auto py-3 flex flex-col items-center gap-2"
            onClick={handleExportJSON}
            disabled={isDisabled}
          >
            <FileJson className="w-5 h-5" />
            <span className="text-xs">JSON</span>
          </Button>

          <Button
            variant="outline"
            className="h-auto py-3 flex flex-col items-center gap-2"
            onClick={handleExportCSV}
            disabled={isDisabled}
          >
            <FileSpreadsheet className="w-5 h-5" />
            <span className="text-xs">CSV</span>
          </Button>

          <Button
            variant="outline"
            className="h-auto py-3 flex flex-col items-center gap-2"
            onClick={handleExportMarkdown}
            disabled={isDisabled}
          >
            <FileText className="w-5 h-5" />
            <span className="text-xs">Markdown</span>
          </Button>
        </div>

        {!data?.verdict && (
          <p className="text-xs text-muted-foreground text-center mt-3">
            Complete verification to enable export
          </p>
        )}
      </div>
    </div>
  );
}
