/**
 * Export Panel Component
 * 
 * EXPORT FORMAT REQUIREMENTS (MANDATORY):
 * - CSV/XLS headers must be horizontal (column-based)
 * - One analysis = one row of metadata values
 * - Timeline events may be appended as additional rows if needed
 * - CSV must be encoded as UTF-8 with BOM
 * - XLS/XLSX must preserve full Unicode support
 * - Filenames in Korean, Japanese, Chinese, and all non-Latin scripts must not break
 * 
 * v1.0 FINAL:
 * - Download All button downloads all reports as single ZIP archive
 */

import { Button } from "@/components/ui/button";
import { FileJson, FileSpreadsheet, FileText, FileType, Download } from "lucide-react";
import JSZip from "jszip";

interface VerdictResult {
  verdict: "AI signal evidence was observed." | "AI signal evidence was not observed." | null;
  authority: "CR-G";
  exceeded_axes: string[];
}

interface ExportData {
  fileName: string;
  fileSize: number;
  duration: number | null;
  sampleRate: number | null;
  bitDepth: number | null;
  channels: number | null;
  codec: string | null;
  fileHash: string | null;
  verdict: VerdictResult | null;
  crgStatus: string | null;
  primaryExceededAxis: string | null;
  timelineMarkers: { timestamp: number; type: string }[];
  analysisTimestamp: string;
}

interface ExportPanelProps {
  data: ExportData | null;
  disabled?: boolean;
}

// Helper to get verdict text from VerdictResult
function getVerdictText(verdict: VerdictResult | null): string {
  return verdict?.verdict || "";
}

function formatDuration(ms: number): string {
  const totalSeconds = Math.floor(ms / 1000);
  const mins = Math.floor(totalSeconds / 60);
  const secs = totalSeconds % 60;
  return `${mins}:${secs.toString().padStart(2, "0")}`;
}

function generatePDFContent(data: ExportData): string {
  const verdictText = getVerdictText(data.verdict) || "Pending";

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>DetectX Audio Verification Report</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
    h1 { color: #0d9488; border-bottom: 2px solid #0d9488; padding-bottom: 10px; }
    h2 { color: #555; margin-top: 30px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }
    th { background: #f5f5f5; }
    .verdict { font-size: 18px; padding: 20px; background: #f0fdf4; border-left: 4px solid #22c55e; margin: 20px 0; }
    .verdict.observed { background: #fffbeb; border-left-color: #f59e0b; }
    .footer { margin-top: 40px; font-size: 12px; color: #888; }
  </style>
</head>
<body>
  <h1>DetectX Audio Verification Report</h1>
  <p><strong>Generated:</strong> ${data.analysisTimestamp}</p>
  
  <h2>File Information</h2>
  <table>
    <tr><th>Filename</th><td>${data.fileName}</td></tr>
    <tr><th>File Size</th><td>${(data.fileSize / 1024 / 1024).toFixed(2)} MB</td></tr>
    <tr><th>Duration</th><td>${data.duration ? formatDuration(data.duration) : "N/A"}</td></tr>
    <tr><th>Sample Rate</th><td>${data.sampleRate ? `${data.sampleRate} Hz` : "N/A"}</td></tr>
    <tr><th>Bit Depth</th><td>${data.bitDepth ? `${data.bitDepth}-bit` : "N/A"}</td></tr>
    <tr><th>Channels</th><td>${data.channels || "N/A"}</td></tr>
    <tr><th>Codec</th><td>${data.codec || "N/A"}</td></tr>
    <tr><th>SHA-256</th><td style="font-family: monospace; font-size: 12px;">${data.fileHash || "N/A"}</td></tr>
  </table>
  
  <h2>Verification Result</h2>
  <div class="verdict ${data.verdict?.verdict === "AI signal evidence was observed." ? "observed" : ""}">
    ${verdictText}
  </div>
  
  <table>
    <tr><th>CR-G Status</th><td>${data.crgStatus || "N/A"}</td></tr>
    ${data.primaryExceededAxis ? `<tr><th>Primary Exceeded Axis</th><td>${data.primaryExceededAxis}</td></tr>` : ""}
  </table>
  
  ${data.timelineMarkers.length > 0 ? `
  <h2>Timeline Events</h2>
  <table>
    <tr><th>#</th><th>Type</th><th>Timestamp</th></tr>
    ${data.timelineMarkers.map((m, i) => `
      <tr>
        <td>${i + 1}</td>
        <td>${m.type}</td>
        <td>${formatDuration(m.timestamp)}</td>
      </tr>
    `).join("")}
  </table>
  ` : ""}
  
  <div class="footer">
    <p>This report contains structural signal evidence only. The system does not estimate probability, attribute authorship, or reference any specific AI model names.</p>
    <p>Generated by DetectX Audio — Audio AI Signal Verification</p>
  </div>
</body>
</html>
  `;
}

function generateJSON(data: ExportData): string {
  const report = {
    reportVersion: "1.0.0",
    generatedAt: data.analysisTimestamp,
    file: {
      name: data.fileName,
      size: data.fileSize,
      duration: data.duration,
      sampleRate: data.sampleRate,
      bitDepth: data.bitDepth,
      channels: data.channels,
      codec: data.codec,
      hash: data.fileHash,
    },
    verification: {
      verdict: getVerdictText(data.verdict),
      verdictCode: data.verdict?.verdict || null,
      crgStatus: data.crgStatus,
      primaryExceededAxis: data.primaryExceededAxis,
    },
    timelineEvents: data.timelineMarkers,
  };
  return JSON.stringify(report, null, 2);
}

/**
 * Generate CSV with horizontal headers (column-based)
 * MANDATORY: UTF-8 with BOM encoding
 * One analysis = one row of metadata values
 */
function generateCSV(data: ExportData): string {
  // Escape CSV values properly for Unicode support
  const escapeCSV = (value: string | number | null | undefined): string => {
    if (value === null || value === undefined) return "";
    const str = String(value);
    // Always quote strings that might contain special characters
    if (str.includes(",") || str.includes('"') || str.includes("\n") || /[^\x00-\x7F]/.test(str)) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  };

  // Horizontal headers (column-based)
  const headers = [
    "Filename",
    "File Size (bytes)",
    "Duration (ms)",
    "Sample Rate (Hz)",
    "Bit Depth",
    "Channels",
    "Codec",
    "SHA-256 Hash",
    "Verdict",
    "CR-G Status",
    "Primary Exceeded Axis",
    "Analysis Timestamp",
  ];

  // One row of metadata values
  const values = [
    escapeCSV(data.fileName),
    data.fileSize,
    data.duration || "",
    data.sampleRate || "",
    data.bitDepth || "",
    data.channels || "",
    escapeCSV(data.codec),
    escapeCSV(data.fileHash),
    escapeCSV(getVerdictText(data.verdict)),
    escapeCSV(data.crgStatus),
    escapeCSV(data.primaryExceededAxis),
    escapeCSV(data.analysisTimestamp),
  ];

  let csv = headers.join(",") + "\n" + values.join(",");

  // Append timeline events as additional rows if present
  if (data.timelineMarkers.length > 0) {
    csv += "\n\n";
    csv += "Timeline Events\n";
    csv += "Index,Event Type,Timestamp (ms)\n";
    data.timelineMarkers.forEach((marker, idx) => {
      csv += `${idx + 1},${escapeCSV(marker.type)},${marker.timestamp}\n`;
    });
  }

  return csv;
}

function generateMarkdown(data: ExportData): string {
  const verdictText = getVerdictText(data.verdict) || "Pending";

  let md = `# DetectX Audio Verification Report

**Generated:** ${data.analysisTimestamp}

## File Information

| Field | Value |
|-------|-------|
| Filename | ${data.fileName} |
| File Size | ${(data.fileSize / 1024 / 1024).toFixed(2)} MB |
| Duration | ${data.duration ? formatDuration(data.duration) : "N/A"} |
| Sample Rate | ${data.sampleRate ? `${data.sampleRate} Hz` : "N/A"} |
| Bit Depth | ${data.bitDepth ? `${data.bitDepth}-bit` : "N/A"} |
| Channels | ${data.channels || "N/A"} |
| Codec | ${data.codec || "N/A"} |
| SHA-256 | \`${data.fileHash || "N/A"}\` |

## Verification Result

> **${verdictText}**

| Metric | Value |
|--------|-------|
| CR-G Status | ${data.crgStatus || "N/A"} |
${data.primaryExceededAxis ? `| Primary Exceeded Axis | ${data.primaryExceededAxis} |` : ""}

`;

  if (data.timelineMarkers.length > 0) {
    md += `## Timeline Events

| # | Type | Timestamp |
|---|------|-----------|
${data.timelineMarkers.map((m, i) => `| ${i + 1} | ${m.type} | ${formatDuration(m.timestamp)} |`).join("\n")}

`;
  }

  md += `---

*This report contains structural signal evidence only. The system does not estimate probability, attribute authorship, or reference any specific AI model names.*

*Generated by DetectX Audio — Audio AI Signal Verification*
`;

  return md;
}

/**
 * Download file with proper encoding
 * CSV uses UTF-8 with BOM for Excel compatibility
 */
function downloadFile(content: string, filename: string, mimeType: string, addBOM: boolean = false) {
  let finalContent = content;
  
  // Add UTF-8 BOM for CSV files to ensure Excel opens with correct encoding
  if (addBOM) {
    finalContent = "\uFEFF" + content;
  }
  
  const blob = new Blob([finalContent], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function ExportPanel({ data, disabled = false }: ExportPanelProps) {
  /**
   * Safely extract base filename for export
   * Handles Unicode filenames (Korean, Japanese, Chinese, etc.)
   */
  const getBaseFileName = (fileName: string): string => {
    // Remove extension while preserving Unicode characters
    const lastDotIndex = fileName.lastIndexOf(".");
    if (lastDotIndex > 0) {
      return fileName.substring(0, lastDotIndex);
    }
    return fileName;
  };

  /**
   * Sanitize filename for safe download
   * Preserves Unicode but removes potentially problematic characters
   */
  const sanitizeFileName = (fileName: string): string => {
    // Remove characters that might cause issues in filenames
    // but preserve Unicode letters and numbers
    return fileName.replace(/[<>:"/\\|?*\x00-\x1f]/g, "_");
  };

  const handleExportPDF = () => {
    if (!data) return;
    const content = generatePDFContent(data);
    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(content);
      printWindow.document.close();
      printWindow.print();
    }
  };

  const handleExportJSON = () => {
    if (!data) return;
    const content = generateJSON(data);
    const baseName = sanitizeFileName(getBaseFileName(data.fileName));
    downloadFile(content, `${baseName}_report.json`, "application/json");
  };

  const handleExportCSV = () => {
    if (!data) return;
    const content = generateCSV(data);
    const baseName = sanitizeFileName(getBaseFileName(data.fileName));
    // Add UTF-8 BOM for CSV to ensure proper encoding in Excel
    downloadFile(content, `${baseName}_report.csv`, "text/csv", true);
  };

  const handleExportMarkdown = () => {
    if (!data) return;
    const content = generateMarkdown(data);
    const baseName = sanitizeFileName(getBaseFileName(data.fileName));
    downloadFile(content, `${baseName}_report.md`, "text/markdown");
  };

  /**
   * Download All - Bundle all reports as single ZIP archive
   * v1.0 FINAL: No confirmation dialog required
   */
  const handleDownloadAll = async () => {
    if (!data) return;
    
    const baseName = sanitizeFileName(getBaseFileName(data.fileName));
    const zip = new JSZip();
    
    // Add all report formats to ZIP
    const htmlContent = generatePDFContent(data);
    zip.file(`${baseName}_report.html`, htmlContent);
    
    const jsonContent = generateJSON(data);
    zip.file(`${baseName}_report.json`, jsonContent);
    
    // CSV with UTF-8 BOM
    const csvContent = "\uFEFF" + generateCSV(data);
    zip.file(`${baseName}_report.csv`, csvContent);
    
    const mdContent = generateMarkdown(data);
    zip.file(`${baseName}_report.md`, mdContent);
    
    // Generate and download ZIP
    const zipBlob = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(zipBlob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${baseName}_detectx_reports.zip`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const isDisabled = disabled || !data || !data.verdict;

  return (
    <div className="forensic-panel">
      <div className="forensic-panel-header">Export Report</div>
      <div className="forensic-panel-content">
        {/* Download All Button - Prominent placement */}
        <Button
          variant="default"
          className="w-full mb-4 bg-forensic-cyan hover:bg-forensic-cyan/90 text-black font-medium"
          onClick={handleDownloadAll}
          disabled={isDisabled}
        >
          <Download className="w-4 h-4 mr-2" />
          Download All & Stems (ZIP)
        </Button>

        <div className="grid grid-cols-2 gap-3">
          <Button
            variant="outline"
            className="h-auto py-3 flex flex-col items-center gap-2"
            onClick={handleExportPDF}
            disabled={isDisabled}
          >
            <FileType className="w-5 h-5" />
            <span className="text-xs">PDF</span>
          </Button>

          <Button
            variant="outline"
            className="h-auto py-3 flex flex-col items-center gap-2"
            onClick={handleExportJSON}
            disabled={isDisabled}
          >
            <FileJson className="w-5 h-5" />
            <span className="text-xs">JSON</span>
          </Button>

          <Button
            variant="outline"
            className="h-auto py-3 flex flex-col items-center gap-2"
            onClick={handleExportCSV}
            disabled={isDisabled}
          >
            <FileSpreadsheet className="w-5 h-5" />
            <span className="text-xs">CSV</span>
          </Button>

          <Button
            variant="outline"
            className="h-auto py-3 flex flex-col items-center gap-2"
            onClick={handleExportMarkdown}
            disabled={isDisabled}
          >
            <FileText className="w-5 h-5" />
            <span className="text-xs">Markdown</span>
          </Button>
        </div>

        {!data?.verdict && (
          <p className="text-xs text-muted-foreground text-center mt-3">
            Complete verification to enable export
          </p>
        )}
      </div>
    </div>
  );
}
